services:
  - type: web
    name: legal-service
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 15m
      - key: JWT_REFRESH_EXPIRATION
        value: 7d
      - key: PORT
        value: 3000
